import type { Metadata } from "next";
import { Inter, Noto_Sans_TC } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import { Github, Instagram } from "lucide-react";
import { YZUICLogo, StrawberryPieLogo } from "./svg_components/Logos";
import Navbar from "./components/nav"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const notoSansTC = Noto_Sans_TC({
  variable: "--font-noto-sans-tc",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Do-NUT",
  icons: [
    { rel: "icon", type: "image/svg+xml", url: "/favicon/leaf.svg" },
    { rel: "icon", type: "image/png", sizes: "32x32", url: "/favicon/leaf.png" },
  ],
  description: "Made by Timeout Studio."
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-tw" className={`${inter.variable} ${notoSansTC.variable} `}>
      <body className="">
        <div className={styles.wrapper}>
          <Navbar/>
          <main className={styles.content}>
            {children}{" "}
          </main>
          <footer className="bg-donut-bg-2 p-6 text-donut-p-tiny ">
            <div className="flex justify-between">
              <object data="/TimoutStudioLogo.svg" className="" />
              <div className="flex justify-between items-center gap-2">
                <a href="./">
                  <Github className="h-4.5 w-4.5" />
                </a>
                <a href="https://www.instagram.com/donut_timeout/">
                  <Instagram className="h-4.5 w-4.5" />
                </a>
              </div>
            </div>
            <p className="p-1">元智大學資訊傳播學系第 28 屆畢業展 － 互動組</p>
            <div className="">
              <div>
                <div className="block mt-4">
                  <div className="m-1 flex gap-1 items-center">
                    <p>主辦單位：</p>
                    <a href="https://infocom.yzu.edu.tw/">
                      <YZUICLogo className="text-donut-text-white" />
                    </a>
                    <a href="https://strawberrypie.tw/">
                      <StrawberryPieLogo className="text-donut-text-white" />
                    </a>
                  </div>
                  <div className="m-1 flex gap-1 items-center">
                    <p>協辦單位：</p>
                    <object data="/SongshanLogo.svg"></object>
                    <object data="/TaoyuanLogo.svg"></object>
                    <object data="/MOELogo.svg"></object>
                  </div>
                </div>
                <p className="p-1 pt-3 text-donut-text-gray">
                  Copyright © 2025 Timeout Studio. All rights reserved.
                </p>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
