import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Noto_Sans_TC,
  Dela_Gothic_One,
} from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import { Menu, Github, Instagram } from "lucide-react";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const notoSansTC = Noto_Sans_TC({
  variable: "--font-noto-sans-tc",
  subsets: ["latin"],
});

const delaGothic = Dela_Gothic_One({
  variable: "--font-dela",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Do-NUT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-tw">
      <body className="">
        <div className={styles.wrapper}>
          <nav className="h-16 nav-gradient flex justify-between items-center  p-4">
            <object data="/DonutLogo.svg" className="mb-1" />
            <Menu className="text-donut-prim" />
            <div className="fixed h-8 w-100vw top-0"></div>
          </nav>
          <main className={styles.content}>
            {children}{" "}
            <p>
              cupiditate eaque aperiam dignissimos ullam id consequatur
              inventore eius commodi laboriosam sit ipsa numquam sint. Ullam
              distinctio et iusto nobis quos cum vitae ab, odit rem ipsa cumque
              in reprehenderit maiores. Nulla provident dolor vel, voluptates
              alias suscipit eum! Consectetur dolores maiores temporibus
              distinctio.upiditate eaque aperiam dignissimos ullam id
              consequatur inventore eius commodi laboriosam sit ipsa numquam
              sint. Ullam distinctio et iusto nobis quos cum vitae ab, odit rem
              ipsa cumque in reprehenderit maiores. Nulla provident dolor vel,
              voluptates alias suscipit eum! Consectetur dolores maiores
              temporibus distinctio.upiditate eaque aperiam dignissimos ullam id
              consequatur inventore eius commodi laboriosam sit ipsa numquam
              sint. Ullam distinctio et iusto nobis quos cum vitae ab, odit rem
              ipsa cumque in reprehenderit maiores. Nulla provident dolor vel,
              voluptates alias suscipit eum! Consectetur dolores maiores
              temporibus distinctio.upiditate eaque aperiam dignissimos ullam id
              consequatur inventore eius commodi laboriosam sit ipsa numquam
              sint. Ullam distinctio et iusto nobis quos cum vitae ab, odit rem
              ipsa cumque in reprehenderit maiores. Nulla provident dolor vel,
              voluptates alias suscipit eum! Consectetur dolores maiores
              temporibus distinctio.upiditate eaque aperiam dignissimos ullam id
              consequatur inventore eius commodi laboriosam sit ipsa numquam
              sint. Ullam distinctio et iusto nobis quos cum vitae ab, odit rem
              ipsa cumque in reprehenderit maiores. Nulla provident dolor vel,
              voluptates alias suscipit eum! Consectetur dolores maiores
              temporibus distinctio.
            </p>
          </main>
          <footer className="bg-donut-bg-2 p-6">
            <div className="flex justify-between">
              <object data="/TimoutStudioLogo.svg" className="" />
              <div className="flex justify-between items-center gap-2">
                <Github className="h-4.5 w-4.5" />
                <Instagram className="h-4.5 w-4.5" />
              </div>
            </div>
            <p className="p-1 text-donut-p-tiny">
              元智大學資訊傳播學系第 28 屆畢業展 － 互動組
            </p>
            <div className="flex">
              <p className="mx-auto p-1 pt-3 text-donut-p-tiny text-donut-text-gray">
                Copyright © 2025 Timeout Studio.
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
